---
title: "Install R Packages"
description: |
  A personal documentation.
author:
  - name: Mark Chen
    url: https://markgene.github.io/
    affiliation: St Jude Children's Research Hospital
    affiliation_url: https://www.stjude.org/
date: "`r Sys.Date()`"
output: 
  radix::radix_article:
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# In one-go

This never works :-(

## Packages from CRAN

```{r}
##################### Packages from CRAN
cran_pkgs <-
  c(
    "BiocManager",
    "coin",
    "covr",
    "DataExplorer",
    "devtools",
    "httr",
    "knitr",
    "mice",
    "party",
    "rematch",
    "rematch2",
    "rmarkdown",
    "selectr",
    "stringr",
    "tidyverse",
    "usethis",
    "webshot"
  )

# install.packages(cran_pkgs[!cran_pkgs %in% installed.packages()],
#                  dependencies = c("Depends", "Suggests"))

install.packages(cran_pkgs[!cran_pkgs %in% installed.packages()])

webshot::install_phantomjs()
```

## GitHub

```{r}
package_names <- function(x) {
  stringr::str_extract(x, "\\/.*$") %>%
    stringr::str_remove(., "^/")
}

github_packages <- c(
  "ropenscilabs/available",
  "rstudio/blogdown",
  "rstudio/bookdown",
  "jennybc/cellranger",
  "ropenscilabs/skimr",
  "ismayc/thesisdown",
  "tidymodels/tidymodels",
  "markgene/yamat",
  "markgene/yamatCN"
)

# devtools::install_github(
#   github_packages[!package_names(github_packages) %in% installed.packages()],
#   force = TRUE,
#   dependencies = c("Depends", "Suggests")
# )

devtools::install_github(
  github_packages[!package_names(github_packages) %in% installed.packages()],
  force = TRUE
)
```

## Bioconductor

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()

bioc_packages <- c(
  "conumee",
  "GenVisR",
  "IlluminaHumanMethylationEPICanno.ilm10b2.hg19",
  "IlluminaHumanMethylationEPICanno.ilm10b3.hg19",
  "IlluminaHumanMethylationEPICanno.ilm10b4.hg19",
  "minfi",
  "minfiDataEPIC"
  # "scRNAseq", 
  # "simpleSingleCell"
)

# ._ <- sapply(
#   bioc_packages[! bioc_packages %in% installed.packages()],
#   function(pkg) BiocManager::install(pkg, version = "devel")
# )

._ <- sapply(
  bioc_packages[! bioc_packages %in% installed.packages()],
  function(pkg) BiocManager::install(pkg)
)
```

# Log

```{r}
######################### 2019-11-22 ########################
install.packages("BiocManager")
install.packages("knitr")
install.packages("webshot")
# Install openssl by homebrew before installing the R package
install.packages("openssl")
install.packages("httr")
install.packages("usethis")
install.packages("covr")
install.packages("devtools")
install.packages("coin")
install.packages("party")
# Tidyverse
install.packages("tidyverse")

install.packages("DataExplorer")
install.packages("mice")

```




